CREATE DATABASE queuing;
USE queuing;

CREATE TABLE queue (
  id INT(11) NOT NULL AUTO_INCREMENT,
  queue_number VARCHAR(255) NOT NULL,
  floor VARCHAR(11) NOT NULL,
  party_size INT(11) NOT NULL,
  queue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(255) NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (id)
);

CREATE TABLE floor1 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  queue_number VARCHAR(255) NOT NULL,
  floor VARCHAR(11) NOT NULL,
  party_size INT(11) NOT NULL,
  queue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(255) NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (id)
);

CREATE TABLE floor2 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  queue_number VARCHAR(255) NOT NULL,
  floor VARCHAR(11) NOT NULL,
  party_size INT(11) NOT NULL,
  queue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(255) NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (id)
);

CREATE TABLE floor3 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  queue_number VARCHAR(255) NOT NULL,
  floor VARCHAR(11) NOT NULL,
  party_size INT(11) NOT NULL,
  queue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(255) NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (id)
);

CREATE TABLE floor6 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  queue_number VARCHAR(255) NOT NULL,
  floor VARCHAR(11) NOT NULL,
  party_size INT(11) NOT NULL,
  queue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(255) NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (id)
);

CREATE TABLE priority_queue (
  id INT(11) NOT NULL AUTO_INCREMENT,
  queue_number VARCHAR(255) NOT NULL,
  floor VARCHAR(11) NOT NULL,
  party_size INT(11) NOT NULL,
  queue_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(255) NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (id)
);

ALTER TABLE queue AUTO_INCREMENT = 1;
ALTER TABLE floor1 AUTO_INCREMENT = 1;
ALTER TABLE floor2 AUTO_INCREMENT = 1;
ALTER TABLE floor3 AUTO_INCREMENT = 1;
ALTER TABLE floor6 AUTO_INCREMENT = 1;
ALTER TABLE priority_queue AUTO_INCREMENT = 1;